[project]
name = "pdf-to-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.38.17",
    "fastapi[standard]>=0.115.12",
    "num2words>=0.5.14",
    "pdfplumber>=0.11.6",
]
